[phases.setup]
nixPkgs = [
  "python312",
  "python312Packages.requests",
  "python312Packages.anthropic",
  "python312Packages.pyyaml",
  "python312Packages.python-frontmatter",
  "nodejs_20"
]

[variables]
NIXPACKS_NO_CACHE = "1"
